define(["angular",
        "utils/resizer.directive",
        "utils/draggable.directive",
        "utils/stopEvent.directive"
        ],
    function(angular){
        angular.module('utils',["utils.resizer",
                                "utils.draggable",
                                "utils.stopEvent"
                                ]);
    }
);
