define(["angular",
        "layout/vizReportContainer.directive",
        "layout/vizToolBox.directive",
        "layout/vizReportLayout.directive"
    ],function(angular){
    //http://angular-ui.github.io/bootstrap/
    angular.module('vizDirectives.layout',[
                    'vizDirectives.layout.vizReportContainer',
                    "vizDirectives.layout.vizToolBox",
                    "vizDirectives.layout.vizReportLayout",
                    "vizDirectives.layout.vizSheetConfig"
                    ]);
});